name: palmeras
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pip
  - tensorflow=2.8.0
  - scipy
  - pandas
  - gdal=3.5.0
  - pip:
      - opencv-python-headless
      - fiona
      - scikit-learn-intelex
      - imgaug
      - imagecorruptions
      - scikit-image==0.19.3    
      - matplotlib==3.5.1
      - rasterio==1.2.10
      - jupyter

